//Products//

export const CREATE_PRODUCT = "CREATE_PRODUCT";
//export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_BY_SEARCH = "GET_PRODUCT_BY_SEARCH";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY";
export const ADD_CATEGORY_TO_PRODUCT = "ADD_CATEGORY_TO_PRODUCT";
export const DELETE_PRODUCT_CATEGORY = "DELETE_PRODUCT_CATEGORY";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const EDIT_PRODUCT_STOCK = "EDIT_PRODUCT_STOCK";
export const CREATE_PRODUCT_REVIEW = "CREATE_PRODUCT_REVIEW";
//Categories

export const ADD_CATEGORY = "ADD_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORY_BY_ID = "GET_CATEGORY_BY_ID";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const GET_CATEGORY_BY_PRODUCT_ID = "GET_CATEGORY_BY_PRODUCT_ID";

//Cart

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const INCREMENT_SIZE_AMOUNT = "INCREMENT_SIZE_AMOUNT";
export const DECREMENT_SIZE_AMOUNT = "DECREMENT_SIZE_AMOUNT";
export const DELETE_PRODUCT_CART = "DELETE_PRODUCT_CART";
export const CLEAR_CART = "CLEAR_CART";
export const USER_ORDER_DETAILS = "USER_ORDER_DETAILS";
//User

export const USER_REGISTER = "USER_REGISTER";
export const GET_USERS = "GET_USERS";
export const USER_DATA = "USER_DATA";
export const USER_LOGIN = "USER_LOGIN";

export const USER_PROMOTE = "USER_PROMOTE";
export const USER_DEGRADE = "USER_DEGRADE";
export const USER_DELETE = "USER_DELETE";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_ME = "USER_ME";
export const USER_DETAILS = "USER_DETAILS";
export const USER_UPDATE = "USER_UPDATE";
export const PASSWORD_RESET = "PASSWORD_RESET";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const PASSWORD_LINK_RESET = "PASSWORD_LINK_RESET";

//Order

export const GET_ORDERS = "GET_ORDERS";
export const CHANGE_ORDER_STATE = "CHANGE_ORDER_STATE";
export const GET_FILTER_ORDERS = "GET_FILTER_ORDERS";
export const GET_ORDERS_STATE_USERID = "GET_ORDERS_STATE_USERID";
export const GET_EXACT_ORDER = "GET_EXACT_ORDER";
export const ADD_ORDER_DETAIL = "ADD_ORDER_DETAIL";
export const ALL_ORDERS_STATEID = "ALL_ORDERS_STATEID";
export const ALL_ORDERS_FILTER_BY_STATE = "ALL_ORDERS_FILTER_BY_STATE";
export const SEND_PACKAGE_EMAIL = "SEND_PACKAGE_EMAIL";
export const CREATE_ACTIVE_ORDER = "CREATE_ACTIVE_ORDER";

//Checkout

export const MAKE_PAYMENT = "MAKE_PAYMENT";
export const MERCADOPAGO_PAYMENT = "MERCADOPAGO_PAYMENT";
export const MERCADO_PAGO_CHECKOUT = "MERCADO_PAGO_CHECKOUT";